---
title: "Transitioning from Academia to Industry"
lead: "Learn about the greatest differences between a data science role in academia and a software engineering role in industry. How to prepare for the transition?"
author: Matthias Döring
date: '2019-12-02'
description: "Transitioning from academia to industry can be challenging. Based on working as a data scientist in research and as a DevOps engineer in industry, I share what I find are the greatest differences between working in academia vs industry. Finally, I offer some tips on how to prepare for an industry job."
slug: "transitioning-from-academia-to-industry"
downloadRmd: false
categories:
  - commentary
tags:
thumbnail: "/post/commentary/from_academia_to_industry_avatar.png"
---
Having recently transitioned from academia to industry, I'd like to share what I found are the greatest differences between working in industry and academia. Since this article is based on my personal experiences, I would first like introduce my respective roles in research and in industry. After that, I will summarize the main differences between industry and academia. Finally, I offer some pieces of advice regarding how to prepare for an industry job when transitioning from academia.

## My Roles in Academia and Industry

### Academia
My experiences in research comes from my time at the [Max Planck Institute for Informatics](http://www.mpi-inf.mpg.de) where I spent more than four years as a PhD student in bioinformatics. This role was basically a data science role where the applications where mainly in the virological and immunological domain. In contrast to many PhD positions, I didn't have to do teaching, so I could spend all of my time on research.

As a bioinformatics PhD student, I distributed my time roughly in the following way:

* 40%: Development of algorithms and their implementation as software tools
* 30%: Development of machine learning models
* 15%: Provision of services in statistics and bioinformatics (e.g. NGS data analysis and evaluation of clinical studies)
* 10%: Activities in the scientific community (e.g. attending conferences or working on reviews, papers, talks, and posters)
* 5%: Development of soft skills via grad school trainings

### Industry

Having handed in my dissertation in January 2019, I joined [DB Systel](http://www.dbsystel.de), the IT-subsidiary of Deutsche Bahn. After about a month of networking within the company I joined a promising project in my current role as a DevOps C++ software engineer. In this role, I'm distributing my time in the following way:

* 40%: C++ software engineering (including testing and code reviews)
* 20%: Development of Jenkins pipelines using Groovy
* 20%: Scrum events (e.g. daily, planning, retro, refinement) and other project events (developer meeting, communities of practice)
* 10%: DevOps tasks (e.g. deployments, monitoring, configuration)
* 5%: Company events (e.g. workshops, coding dojos/retreats, department meetings)
* 5%: Professional trainings 

## The Main Differences between Academia and Industry

### Size of Organizations

One of the main differences between academia and industry is the size of their respective organizations. Most research organizations correspond to medium-sized companies with less than 250 employees. Corporations, on the other hand, are frequently much larger than that. For example, Walmart, the largest privately owned enterprise, has more than two million employees.

In my case, I moved from an institution with about 250 employees to a company with roughly 4,400 employees whose parent enterprise has about 320,000 employees. This was the first time that I experienced standardized processes and corporate compliance. The IT infrastructure is also more complex. Let's consider the intranet as an example. At my previous institute, the only available intranet services were
email and the web pages of individual research groups. At my current company, on the other hand, there are probably more than twenty available services for tasks such as social networking, taking vacation, booking working hours, or ordering soft- and hardware.

### Importance of Networking

Networking is important in both academia and industry. However, I find that networking is more important in industry. One reason for this is that academic organizations are usually smaller than industrial organizations. In academia, you implicitly get to know your colleagues because they are probably sitting in a room nearby, so it's easy to drop in and have a chat. Since industry organizations often have locations in multiple cities throughout the world, one must put more effort into forming connections.

Another difference lies in the potential benefits of networking in academia and industry. Although successful, large-scale collaborations exist in academia, they are not the norm. Possible reasons for this include the fact that research is often theoretical and extremely focused so that there are few candidates for collaboration. In industry, on the other hand, the work is more practical and more manpower is needed. Thus, collaboration is a must and networking is necessary to hoist synergies.

For an individual, the importance of networking stems from the fact that one's path within the corporation can be heavily influenced by one's network. Imagine that there is a really cool, innovative new project starting at your company. However, if you don't know any person involved in the project, you will likely never get an opportunity to join. So, try to forge as many substantial personal bonds as you can.

### Atmosphere at Work

The atmosphere in academic and industry office spaces can be quite different. The archetype of academic work is serene and quiet, while industry is bustling with life. In my experiences, this is true for the most part. In academia I had my own private office and was seldomly disturbed. In industry, on the other hand, I'm situated in an open-plan office that I share with about twenty people, which means there is a lot going on: phones are ringing, people are talking, and there are more interruptions.

Both working styles have their pros and cons. While academic isolation allows for focused thought, industrial openness fosters collaboration. If you prefer to have your quiet, I'd recommend you to get your hands on some good noise-cancelling earphones.

### Amount of Meetings

In industry there are way more meetings than in academia. As a PhD student, the only meetings I attended where the weekly meetings with my supervisor and with my research group. In my current position in industry, on the other hand, I have about two meetings per day. Most of these meetings are Scrum meetings and project-specific meetings but there are also organizational meetings.

Having to attend many meetings can make you feel like you're not advancing in your work. However, it is important to recognize that you can actually have a much bigger impact in a meeting than based on your individual work. For example, if you can convince five people in a meeting to follow your approach to solving a problem this is much more valuable than you alone following that approach. Since meetings are often not as efficient as they could be, you shouldn't be afraid to take the lead.

### Diversity

The people you will meet in industry will often have more diverse backgrounds than those you will meet in academia. Let's consider some aspects in which industry is more diverse than academia:

| Characteristic            | Academia                           | Industry         |
|-------------------|------------------------------------|------------------------------------|
| Roles                | PhD students, postdocs, professors | Software engineers, software architects, testers, operations, business analysts/engineers, data scientists, project leads, department heads                 |
| Age                       | Ages concentrated between 25 and 40     | Broad age spectrum |
| Education | University-trained | Self-trained, vocational training, technical college, university                 |

Although [diversity brings many benefits](https://www.wonolo.com/blog/6-benefits-of-having-a-diverse-workforce), there are also challenges associated with diversity. One of these is communication. As an example, consider people with different professional backgrounds such as a software engineer and a project manager. While a conversation with the first could involve many intricate details, a conversation with the latter would likely entail only the few aspects that are actually relevant for the business. So, be prepared to adjust your communication style in dependence on your audience.

### Hierarchies

Academics often interact on a level playing field despite the existence of hierarchies ranging from research assistants, PhD students, and postdocs to professors. In industry, hierarchies are ubiquitous and complex. First, there's the hierarchy of specialists and second, there's the hierarchy of managers. For example, as a data science, you may move through four levels of expertise: from junior data scientist to data scientist to senior data scientist, and finally to lead data scientist. Looking at management careers, there are team heads, department heads, division heads, and finally, the board of directors.

So, what's the difference between academia and industry? In academia, you're likely going to have regular meetings with the person at the top of the hierarchy, your professor and beside him, there are likely few people that tell you what you are supposed to do. While the context of your research is somehow limited by the interests of your professor, it is unlikely that he will tell you exactly what to do but rather offer guidance. In industry, on the other hand, a project's technical lead
will make the crucial decisions and you will have to adhere to those decisions. The same goes for the management hierarchy: as a non-managing employee there is little possibility to influence decisions even at the lowest levels of the management hierarchy and you have to live with the decisions that are made.

While agile Scrum teams do away with the concept of hierarchies, there is still the concept of roles. For example, it's the product owner's responsibility to order the backlog, so as a member of the development team you cannot determine what you are going to work on next. So, all in all, expect that you will have less freedom in industry than in academia.

### Scale of Projects

The scale of industrial projects is often much larger (e.g. 50 people) than those in academia (e.g. 3 people). As a consequence, the scope of the work in industry is different. In academia, it is easy to have a grasp about everything that is going on in a project and one will likely work on all of the project's aspects. In industry, however, there are often specialists for individual tasks, which make up only a small fraction of the whole project. 

So, in an industry position, do not expect that you're supposed to know all the details of the project you're working on. Instead you should know a lot about the current technologies that are relevant for the work that you're doing. 

## Preparing for an Industry Job

When transitioning to industry, I think that experience is the best teacher. Nevertheless, I'd recommend the following activities in preparation for an industry position:

* **Learn about corporate organizational structures:** Being able to understand the complex structures of corporations will help you find a fitting employer and settling in. For example, you should know how to differentiate between traditional and flat hierarchies.
* **Improve your soft skills:** Soft skills such as networking, leadership, negotiation, and moderation are critical in industry, so try to improve upon them.
* **Improve your technical skills:** Technical skills are way more important in industry than in academia. When job hunting, look for the top-3 technical skills and improve them, for example, using online platforms such as [Udemy](https://www.udemy.com) or [Coursera](https://www.coursera.org).
* **Adjust your expectations:** Be aware that you will have less freedom in industry and that it will be harder to focus due to the different work environment. Accept that it will take you a bit of time to adapt to the new environment.
