---
title: "The 5 Skills of Successful PhD Students"
lead: "The soft skills you need to be a successful PhD student."
author: Matthias Döring
date: '2019-12-25'
description: "Doing a PhD requires considerable scientific and technical skills. To be a successful PhD student, these hard skills must be complemented by an array of soft skills. In this post, I delineate what I find are the most important soft skills for PhD students." 
slug: "5-skills-successful-phd-students"
downloadRmd: false
categories:
  - commentary
tags:
thumbnail: "/post/commentary/phd_success_formula_soft_skills.jpeg"
---

A PhD is not only a test of professional aptitude but also a test of character. 
Looking back at my time as a PhD student, I can say that it has been [a taxing but equally rewarding time](https://medium.com/darius-foroux/the-purpose-of-life-is-not-happiness-its-usefulness-65064d0cdd59) that I wouldn't exchange for anything in the world. Doing a PhD has not only improved my scientific and technical understanding but has also strengthened my character.

In this post I describe five characteristics that I found to be helpful in successfully completing my PhD. 

## 1. Self-Reliance

Doing a PhD, self-reliance is essential. Why? You need to pursue projects yourself with miniscule external oversight. This means that you continually need to motivate yourself and need to develop strategies for tackling the challenges along the way.

Of course, you have a supervisor to guide you during your studies. While it's extremely important to have a good relationship with your supervisor, you also shouldn't grow too dependent on him. For example, when my supervisor left for a faculty position at another university, I had to rely on myself much more than before. 

You should not expect your supervisor's assistance to be a silver bullet to all of your problems for the following reasons:

* **You are the expert:** Having worked on a topic for some time, you should be the expert. So, in many cases, your supervisor may only be able to point you in the right direction and you still have to figure out the solution yourself.
* **There is not enough time:** Your supervisor is probably a very busy person. Therefore, he may not have time to answer all of your questions.
* **You may be hurting yourself:** There is nothing wrong with asking questions but you may be hurting yourself if you overdo it. First, you may grow too dependent on your supervisor. Second, you lose out on a chance to develop your own problem solving skills.

## 2. Commitment

A PhD requires a tremendous investment of time and energy. When I started my PhD, I knew that I would have to commit the next several years of your life to this task. "Why does a PhD require a greater level of commitment than other degrees?", you may ask. Doing a PhD is challenging in several respects, for example:

* **Knowledge:** You need to dive deep into a single topic with the goal of expanding upon existing knowledge (scope). At the same time, you may also have to deal with several projects at the same time (scale).
* **Motivation:** While other degrees involve pre-defined, continual milestones (i.e. examinations), which serve as a source of external motivation, milestones during a PhD are few and far between (e.g. scientific publications, the dissertation itself).
* **Gratification:** Research takes time and it will often take years until you reap the fruits of your work. If you are in need of instant gratification, a PhD is not for you.

So, to successfully complete a PhD you need a very high level of commitment. However, you should not forget to [maintain an appropriate work-life balance](https://medium.com/the-mission/how-to-achieve-work-life-balance-in-3-hard-steps-451488ffa620). Burning the candle at both ends may threaten your success.

## 3. Resilience

Resilience is the ability to get back on your feet after a major setback. During my PhD I have experienced many setbacks, for example:

* **Manuscript preparation:** It can take a very long time until the final version of a manuscript is prepared. The problem is that one often thinks that version `n` is going to be the final version but in the end it turns out that version `n+x` (with `x > 10`) is the version that is actually submitted. 
* **Manuscript decisions:** It is the norm that journal submissions are rejected. [Journals often accept only 20%](https://www.sciencedirect.com/science/article/abs/pii/S1751157713000710) of submitted manuscripts for publication. Particularly when you submit to high-tier journals first, you will have only small chances of acceptance. Moreover, when you have chosen to submit your work to another journal after an rejection, you will have to go back to the manuscript preparation phase once again.
* **Experiments:** Generating results is time- and resource-intensive. When you are running an experiment and you notice an error several weeks into the work, this means going back to square one.

So, try to see setbacks as part of the journey rather than nuisances.

## 4. Confidence

While pushing to expand the boundaries of knowledge, you will also become aware of your own ignorance. When this happens, it is easy to fall prey to the [imposter syndrome](https://www.youtube.com/watch?v=eqhUHyVpAwE). However, one should realize that this is normal. Even Socrates' once said the following:

    I know that I know nothing.

His statement suggests that a person who is aware of his own ignorance is wiser than the one who is not. Achieving this awareness should be seen as an indicator of growth rather than an indicator of incompetence.

## 5. Emotional Intelligence

Emotional intelligence means awareness of one's own emotions and those of others. As a PhD student, you will work with different stakeholders: your supervisor, your colleagues, your collaborators, etc. Each one of these people has different goals that only partially overlap, for example: 

* **PhD students** want to finish their PhD
* **Supervisors** want to achieve prestigious research results
* **Collaborators** want your work to appear in high-impact journals without sacrifing too much of their time

Due to the differences in goals, conflicts are pre-programmed. However, with emotional intelligence you can navigate your way through conflicts without losing track of your goals. If you know what motivates the people you are working together with, this can go a long way towards fostering emotional understanding.
