@startuml
actor Customer
activate Customer
activate Bike
Customer -> Bike: startLease()
Bike -> Lease : startLease()
activate Lease
Customer -> Bike: unlock()
Customer -> Bike: endLease()
Bike -> Lease : endLease()
Lease -> Invoice : invoice()
activate Invoice
deactivate Invoice
deactivate Lease
Customer -> Bike: lock()
@enduml
